# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/convolution.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/convolution.proto',
  package='yolov3',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18protos/convolution.proto\x12\x06yolov3\"\x98\x03\n\x0b\x43onvolution\x12\x13\n\x0bnum_filters\x18\x01 \x02(\x05\x12\x10\n\x08kernel_h\x18\x02 \x02(\x05\x12\x10\n\x08kernel_w\x18\x03 \x02(\x05\x12\x10\n\x08stride_h\x18\x04 \x02(\x05\x12\x10\n\x08stride_w\x18\x05 \x02(\x05\x12\x41\n\x13\x61\x63tivation_function\x18\x06 \x01(\x0e\x32\x1e.yolov3.Convolution.Activation:\x04NONE\x12\x1b\n\x13\x62\x61tch_normalization\x18\x07 \x02(\x08\x12\n\n\x02id\x18\x08 \x02(\x05\x12\x14\n\x08input_id\x18\t \x01(\x05:\x02-1\"\xa9\x01\n\nActivation\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04RELU\x10\x01\x12\x0b\n\x07SIGMOID\x10\x02\x12\x10\n\x0cHARD_SIGMOID\x10\x03\x12\t\n\x05SWISH\x10\x04\x12\x0b\n\x07SOFTMAX\x10\x05\x12\x0c\n\x08SOFTPLUS\x10\x06\x12\x0c\n\x08SOFTSIGN\x10\x07\x12\x08\n\x04TANH\x10\x08\x12\x08\n\x04SELU\x10\t\x12\x07\n\x03\x45LU\x10\n\x12\x0c\n\x08\x45XPONENT\x10\x0b\x12\t\n\x05LEAKY\x10\x0c\";\n\x10\x43onvolutionLayer\x12\'\n\nconv_layer\x18\x01 \x02(\x0b\x32\x13.yolov3.Convolution')
)



_CONVOLUTION_ACTIVATION = _descriptor.EnumDescriptor(
  name='Activation',
  full_name='yolov3.Convolution.Activation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELU', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGMOID', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HARD_SIGMOID', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SWISH', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTMAX', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTPLUS', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTSIGN', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TANH', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELU', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ELU', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXPONENT', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAKY', index=12, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=276,
  serialized_end=445,
)
_sym_db.RegisterEnumDescriptor(_CONVOLUTION_ACTIVATION)


_CONVOLUTION = _descriptor.Descriptor(
  name='Convolution',
  full_name='yolov3.Convolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_filters', full_name='yolov3.Convolution.num_filters', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kernel_h', full_name='yolov3.Convolution.kernel_h', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kernel_w', full_name='yolov3.Convolution.kernel_w', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stride_h', full_name='yolov3.Convolution.stride_h', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stride_w', full_name='yolov3.Convolution.stride_w', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_function', full_name='yolov3.Convolution.activation_function', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_normalization', full_name='yolov3.Convolution.batch_normalization', index=6,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='yolov3.Convolution.id', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_id', full_name='yolov3.Convolution.input_id', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONVOLUTION_ACTIVATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=445,
)


_CONVOLUTIONLAYER = _descriptor.Descriptor(
  name='ConvolutionLayer',
  full_name='yolov3.ConvolutionLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conv_layer', full_name='yolov3.ConvolutionLayer.conv_layer', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=506,
)

_CONVOLUTION.fields_by_name['activation_function'].enum_type = _CONVOLUTION_ACTIVATION
_CONVOLUTION_ACTIVATION.containing_type = _CONVOLUTION
_CONVOLUTIONLAYER.fields_by_name['conv_layer'].message_type = _CONVOLUTION
DESCRIPTOR.message_types_by_name['Convolution'] = _CONVOLUTION
DESCRIPTOR.message_types_by_name['ConvolutionLayer'] = _CONVOLUTIONLAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Convolution = _reflection.GeneratedProtocolMessageType('Convolution', (_message.Message,), dict(
  DESCRIPTOR = _CONVOLUTION,
  __module__ = 'protos.convolution_pb2'
  # @@protoc_insertion_point(class_scope:yolov3.Convolution)
  ))
_sym_db.RegisterMessage(Convolution)

ConvolutionLayer = _reflection.GeneratedProtocolMessageType('ConvolutionLayer', (_message.Message,), dict(
  DESCRIPTOR = _CONVOLUTIONLAYER,
  __module__ = 'protos.convolution_pb2'
  # @@protoc_insertion_point(class_scope:yolov3.ConvolutionLayer)
  ))
_sym_db.RegisterMessage(ConvolutionLayer)


# @@protoc_insertion_point(module_scope)
