# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/modelspecs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/modelspecs.proto',
  package='yolov3',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17protos/modelspecs.proto\x12\x06yolov3\"L\n\nModelSpecs\x12\x14\n\x0cimage_height\x18\x01 \x02(\x05\x12\x13\n\x0bimage_width\x18\x02 \x02(\x05\x12\x13\n\x0bnum_classes\x18\x03 \x02(\x05')
)




_MODELSPECS = _descriptor.Descriptor(
  name='ModelSpecs',
  full_name='yolov3.ModelSpecs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_height', full_name='yolov3.ModelSpecs.image_height', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_width', full_name='yolov3.ModelSpecs.image_width', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='yolov3.ModelSpecs.num_classes', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['ModelSpecs'] = _MODELSPECS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelSpecs = _reflection.GeneratedProtocolMessageType('ModelSpecs', (_message.Message,), dict(
  DESCRIPTOR = _MODELSPECS,
  __module__ = 'protos.modelspecs_pb2'
  # @@protoc_insertion_point(class_scope:yolov3.ModelSpecs)
  ))
_sym_db.RegisterMessage(ModelSpecs)


# @@protoc_insertion_point(module_scope)
