# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/residual.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import convolution_pb2 as protos_dot_convolution__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/residual.proto',
  package='yolov3',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15protos/residual.proto\x12\x06yolov3\x1a\x18protos/convolution.proto\"q\n\rResidualBlock\x12\'\n\nbare_convs\x18\x01 \x03(\x0b\x32\x13.yolov3.Convolution\x12\x15\n\nmultiplier\x18\x02 \x01(\x05:\x01\x31\x12\n\n\x02id\x18\x03 \x02(\x05\x12\x14\n\x08input_id\x18\x04 \x01(\x05:\x02-1\"C\n\x12ResidualBlockLayer\x12-\n\x0eresidual_block\x18\x01 \x02(\x0b\x32\x15.yolov3.ResidualBlock')
  ,
  dependencies=[protos_dot_convolution__pb2.DESCRIPTOR,])




_RESIDUALBLOCK = _descriptor.Descriptor(
  name='ResidualBlock',
  full_name='yolov3.ResidualBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bare_convs', full_name='yolov3.ResidualBlock.bare_convs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='yolov3.ResidualBlock.multiplier', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='yolov3.ResidualBlock.id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_id', full_name='yolov3.ResidualBlock.input_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=172,
)


_RESIDUALBLOCKLAYER = _descriptor.Descriptor(
  name='ResidualBlockLayer',
  full_name='yolov3.ResidualBlockLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='residual_block', full_name='yolov3.ResidualBlockLayer.residual_block', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=241,
)

_RESIDUALBLOCK.fields_by_name['bare_convs'].message_type = protos_dot_convolution__pb2._CONVOLUTION
_RESIDUALBLOCKLAYER.fields_by_name['residual_block'].message_type = _RESIDUALBLOCK
DESCRIPTOR.message_types_by_name['ResidualBlock'] = _RESIDUALBLOCK
DESCRIPTOR.message_types_by_name['ResidualBlockLayer'] = _RESIDUALBLOCKLAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResidualBlock = _reflection.GeneratedProtocolMessageType('ResidualBlock', (_message.Message,), dict(
  DESCRIPTOR = _RESIDUALBLOCK,
  __module__ = 'protos.residual_pb2'
  # @@protoc_insertion_point(class_scope:yolov3.ResidualBlock)
  ))
_sym_db.RegisterMessage(ResidualBlock)

ResidualBlockLayer = _reflection.GeneratedProtocolMessageType('ResidualBlockLayer', (_message.Message,), dict(
  DESCRIPTOR = _RESIDUALBLOCKLAYER,
  __module__ = 'protos.residual_pb2'
  # @@protoc_insertion_point(class_scope:yolov3.ResidualBlockLayer)
  ))
_sym_db.RegisterMessage(ResidualBlockLayer)


# @@protoc_insertion_point(module_scope)
