# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/upsample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/upsample.proto',
  package='yolov3',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15protos/upsample.proto\x12\x06yolov3\"<\n\x08UpSample\x12\x0e\n\x06\x66\x61\x63tor\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x14\n\x08input_id\x18\x03 \x01(\x05:\x02-1\"9\n\rUpSampleLayer\x12(\n\x0eupsample_layer\x18\x01 \x02(\x0b\x32\x10.yolov3.UpSample')
)




_UPSAMPLE = _descriptor.Descriptor(
  name='UpSample',
  full_name='yolov3.UpSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='factor', full_name='yolov3.UpSample.factor', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='yolov3.UpSample.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_id', full_name='yolov3.UpSample.input_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=93,
)


_UPSAMPLELAYER = _descriptor.Descriptor(
  name='UpSampleLayer',
  full_name='yolov3.UpSampleLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upsample_layer', full_name='yolov3.UpSampleLayer.upsample_layer', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=152,
)

_UPSAMPLELAYER.fields_by_name['upsample_layer'].message_type = _UPSAMPLE
DESCRIPTOR.message_types_by_name['UpSample'] = _UPSAMPLE
DESCRIPTOR.message_types_by_name['UpSampleLayer'] = _UPSAMPLELAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpSample = _reflection.GeneratedProtocolMessageType('UpSample', (_message.Message,), dict(
  DESCRIPTOR = _UPSAMPLE,
  __module__ = 'protos.upsample_pb2'
  # @@protoc_insertion_point(class_scope:yolov3.UpSample)
  ))
_sym_db.RegisterMessage(UpSample)

UpSampleLayer = _reflection.GeneratedProtocolMessageType('UpSampleLayer', (_message.Message,), dict(
  DESCRIPTOR = _UPSAMPLELAYER,
  __module__ = 'protos.upsample_pb2'
  # @@protoc_insertion_point(class_scope:yolov3.UpSampleLayer)
  ))
_sym_db.RegisterMessage(UpSampleLayer)


# @@protoc_insertion_point(module_scope)
