# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/yolo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/yolo.proto',
  package='yolov3',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11protos/yolo.proto\x12\x06yolov3\"\xae\x01\n\x04Yolo\x12\x0f\n\x07\x61nchors\x18\x01 \x03(\x05\x12\x13\n\x0bnum_classes\x18\x02 \x02(\x05\x12\x0b\n\x03num\x18\x03 \x02(\x05\x12\x0e\n\x06jitter\x18\x04 \x02(\x02\x12\x18\n\x10ignore_threshold\x18\x05 \x02(\x02\x12\x17\n\x0ftruth_threshold\x18\x06 \x02(\x02\x12\x0e\n\x06random\x18\x07 \x02(\x05\x12\n\n\x02id\x18\x08 \x02(\x05\x12\x14\n\x08input_id\x18\t \x01(\x05:\x02-1\"-\n\tYoloLayer\x12 \n\nyolo_layer\x18\x01 \x02(\x0b\x32\x0c.yolov3.Yolo')
)




_YOLO = _descriptor.Descriptor(
  name='Yolo',
  full_name='yolov3.Yolo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='anchors', full_name='yolov3.Yolo.anchors', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='yolov3.Yolo.num_classes', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='yolov3.Yolo.num', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jitter', full_name='yolov3.Yolo.jitter', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ignore_threshold', full_name='yolov3.Yolo.ignore_threshold', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truth_threshold', full_name='yolov3.Yolo.truth_threshold', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random', full_name='yolov3.Yolo.random', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='yolov3.Yolo.id', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_id', full_name='yolov3.Yolo.input_id', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=204,
)


_YOLOLAYER = _descriptor.Descriptor(
  name='YoloLayer',
  full_name='yolov3.YoloLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='yolo_layer', full_name='yolov3.YoloLayer.yolo_layer', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=251,
)

_YOLOLAYER.fields_by_name['yolo_layer'].message_type = _YOLO
DESCRIPTOR.message_types_by_name['Yolo'] = _YOLO
DESCRIPTOR.message_types_by_name['YoloLayer'] = _YOLOLAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Yolo = _reflection.GeneratedProtocolMessageType('Yolo', (_message.Message,), dict(
  DESCRIPTOR = _YOLO,
  __module__ = 'protos.yolo_pb2'
  # @@protoc_insertion_point(class_scope:yolov3.Yolo)
  ))
_sym_db.RegisterMessage(Yolo)

YoloLayer = _reflection.GeneratedProtocolMessageType('YoloLayer', (_message.Message,), dict(
  DESCRIPTOR = _YOLOLAYER,
  __module__ = 'protos.yolo_pb2'
  # @@protoc_insertion_point(class_scope:yolov3.YoloLayer)
  ))
_sym_db.RegisterMessage(YoloLayer)


# @@protoc_insertion_point(module_scope)
